spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/example?useSSL=false
#        type: com.alibaba.druid.pool.DruidDataSource
server:
    port: 8081
mybatis-plus:
    configuration:
        #关闭驼峰命名
        map-underscore-to-camel-case: false
